map_frame_id:                               odom
robot_base_frame_id:                        pose_node
robot_pose_with_covariance_topic:           /poseStamped_with_covariance_node
robot_pose_cache_size:                      200
input_sources:
  front: # A name to identify the input source
    type: pointcloud # Supported types: pointcloud
    topic: /os1_cloud_node/points
    queue_size: 1
    publish_on_update: true # Wheter to publish the elevation map after a callback from this source.
    sensor_processor:
      type: perfect
track_point_frame_id:                       pose_node
track_point_x:                              0.0
track_point_y:                              0.0
track_point_z:                              0.0
min_update_rate:                            2.0

time_tolerance:                             1.0
time_offset_for_point_cloud:                0.0
sensor_processor/ignore_points_above:       0.4
